name: Rust CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Test Docker authentication
    - name: Verify Docker Authentication
      run: |
        echo "Testing Docker Hub connectivity..."
        docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
        docker pull hello-world
        
    - name: Build and tag Docker image
      run: |
        docker build -t tembolo1284/rust-tcp-finance-server:latest .
        docker tag tembolo1284/rust-tcp-finance-server:latest tembolo1284/rust-tcp-finance-server:${{ github.sha }}

    - name: Push Docker image
      run: |
        docker push tembolo1284/rust-tcp-finance-server:latest
        docker push tembolo1284/rust-tcp-finance-server:${{ github.sha }}
