name: Rust CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install yq
      run: |
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod a+x /usr/local/bin/yq

    - name: Read Docker configuration
      id: docker_config
      run: |
        echo "DOCKER_USERNAME=$(yq eval '.docker_hub.username' .github/workflows/docker_config.yml)" >> $GITHUB_ENV
        echo "DOCKER_TOKEN=$(yq eval '.docker_hub.access_token' .github/workflows/docker_config.yml)" >> $GITHUB_ENV
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose

    - name: Build Docker image
      run: docker build -t rust-tcp-finance-server .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_TOKEN }}
      
    - name: Tag and push Docker image
      run: |
        docker tag rust-tcp-finance-server ${{ env.DOCKER_USERNAME }}/rust-tcp-finance-server:latest
        docker push ${{ env.DOCKER_USERNAME }}/rust-tcp-finance-server:latest
