name: RustTCPFinanceServer CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Build and Test
      run: |
        cargo build --release
        cargo test

    - name: Lint with Clippy
      run: cargo clippy -- -D warnings

    - name: Build Docker Image
      run: |
        docker build -t rust-tcp-finance-server .

    - name: Push Docker Image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        docker tag rust-tcp-finance-server $DOCKER_HUB_USERNAME/rust-tcp-finance-server:latest
        docker push $DOCKER_HUB_USERNAME/rust-tcp-finance-server:latest

