name: Rust CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read Docker configuration
      id: docker_config
      uses: ehealthafrica/actions-read-yaml@v1
      with:
        path: "./.github/workflows/docker_config.yml"  # Updated path
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose

    - name: Build Docker image
      run: docker build -t rust-tcp-finance-server .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ fromJson(steps.docker_config.outputs.data).docker_hub.username }}
        password: ${{ fromJson(steps.docker_config.outputs.data).docker_hub.access_token }}
      
    - name: Tag and push Docker image
      run: |
        docker tag rust-tcp-finance-server ${{ fromJson(steps.docker_config.outputs.data).docker_hub.username }}/rust-tcp-finance-server:latest
        docker push ${{ fromJson(steps.docker_config.outputs.data).docker_hub.username }}/rust-tcp-finance-server:latest
